apps/books/urls.py
from django.urls import path

from apps.books.views import BookListView, BookDetailView, AuthorDetailView, GenreDetailView

app_name = "books"

urlpatterns = [
    path('', BookListView.as_view(), name="book-list"),
    path('<slug:slug>/', BookDetailView.as_view(), name="book-detail"),
    path('author/<int:pk>', AuthorDetailView.as_view(), name="author-detail"),
    path('genre/<int:pk>', GenreDetailView.as_view(), name="genre-detail"),
    # path('<pk>/', GenreView.as_view(), name="book-detail"),
]

apps/users/urls.py
from django.urls import path

from apps.users.views import UserLoginView, UserLogoutView, UserRegisterView, UserProfileView

app_name = "users"
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/<int:pk>', UserProfileView.as_view(), name='profile'),

]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from config.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name="home"),
    path('user/', include("apps.users.urls")),
    path('books/', include("apps.books.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/books/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import CharField, TextField, SlugField, TextChoices, IntegerField, ImageField, URLField, \
    ManyToManyField, ForeignKey, CASCADE, DateField
from apps.shared.models import AbstractModel


class LanguageChoice(TextChoices):
    ENGLISH = "en", "English"
    FRANCE = "fr", "France"
    RUSSIAN = "ru", "Russian"
    ARABIC = "ab", "Arabic"
    UZBEK = "uz", "Uzbek"


class Book(AbstractModel):
    title = CharField(max_length=128)
    slug = SlugField(unique=True)
    description = TextField()
    published = DateField()
    isbn = CharField(max_length=128, unique=True)
    language = CharField(max_length=7, choices=LanguageChoice.choices, default=LanguageChoice.ENGLISH)
    page = IntegerField()
    cover = ImageField(upload_to="books/cover/%Y/%m/%d", default="book_cover.jpg")
    genre = ManyToManyField("books.BookGenre", "books")
    authors = ManyToManyField("books.BookAuthor", "books")


class BookAuthor(AbstractModel):
    first_name = CharField(max_length=56)
    last_name = CharField(max_length=56)
    birthdate = DateField()
    website = URLField()
    avatar = ImageField(upload_to="authors/avatar/%Y/%m/%d")
    about = TextField()


class BookGenre(AbstractModel):
    name = CharField(max_length=128)


class BookReview(AbstractModel):
    book = ForeignKey("books.Book", CASCADE, "reviews")
    user = ForeignKey("users.User", CASCADE, "reviews")
    body = TextField()
    rating = IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    like_count = IntegerField(default=0)

apps/shared/models.py
from django.db.models import Model, DateTimeField


class AbstractModel(Model):
    created_at = DateTimeField(auto_now_add=True)
    updated_at = DateTimeField(auto_now=True)

    class Meta:
        abstract = True

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import ImageField, CharField, ForeignKey, CASCADE, ManyToManyField

from apps.shared.models import AbstractModel


class User(AbstractUser):
    avatar = ImageField(upload_to="users/avatar/%Y/%m/%d", default="user_avatar.jpg")
    middle_name = CharField(max_length=128)


class BookShelf(AbstractModel):
    name = CharField(max_length=128)
    user = ForeignKey("User", CASCADE, 'bookshelf')
    books = ManyToManyField("books.Book", "bookshelves")

apps/users/forms.py
from django import forms
from django.core.exceptions import ValidationError

from apps.users.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)

class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=28)
    password2 = forms.CharField(max_length=28)
    # , widget=forms.TextInput(
    #     attrs={"id": "password", "type": "password"}))
    # avatar = forms.FileField()

    def save(self, commit=True):
        user = super().save(commit)
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 == password2:
            user.set_password(password1)
            user.save()
        else:
            raise ValidationError("Passwords must be match")

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field in self.fields:
    #         self.fields[field].widget.attrs.update({"class": "form-control"})

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "avatar")

apps/books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from apps.books.models import Book, BookAuthor, BookGenre


class BookListView(ListView):
    model = Book
    template_name = "books/book-list.html"
    context_object_name = "books"

class BookDetailView(DetailView):
    model = Book
    slug_url_kwarg = 'slug'
    template_name = "books/book-detail.html"
    context_object_name = "book"

class GenreDetailView(DetailView):
    model = BookGenre
    template_name = "books/genre-detail.html"
    context_object_name = "genre"


class AuthorDetailView(DetailView):
    model = BookAuthor
    template_name = "books/author-detail.html"
    context_object_name = "author"

apps/shared/views.py
from django.shortcuts import render

# Create your views here.

apps/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import DetailView

from apps.users.forms import RegisterForm, LoginForm
from apps.users.models import User


class UserRegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "user/register.html", {"form": form})

    def post(self, request):
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "User successfully registered")
            return redirect('users:login')
        else:
            return render(request, "user/register.html", {"form": form})


class UserLoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, "user/login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=request.POST.get("username"), password=request.POST.get("password"))
            if user is not None:
                login(request, user)
                messages.success(request, "user succesfully loged in")
                return redirect("home")
            else:
                messages.warning(request, "User not found")
                return redirect("users:login")
        else:
            return render(request, "user/login.html", {"form": form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request,'user/logout.html')

    def post(self, request):
        messages.info(request, f"{request.user.username} user successfulley loged out")
        logout(request)
        return redirect("users:login")


class UserProfileView(LoginRequiredMixin, DetailView):
        model = User
        template_name = "user/profile.html"
        context_object_name = "user"

config/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, "home.html")

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Bootstrap demo
        {% endblock %}
    </title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Goodreads Clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'books:book-list' %}">Books</a>
                    </li>
                </ul>
            </div>
            <div class="me-5">
                            {% if user.is_authenticated %}
                
                <ul type="none" class="me-5">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
            
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'users:profile' user.pk %}">Profile</a></li>
                        </ul>
                    </li>
                </ul>
                            {% else %}
                <ul type="none" class="me-5">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Profile
                        </a>
                        <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'users:login' %}">Login</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'users:register' %}">Register</a></li>
                        </ul>
                    </li>
                </ul>
                            {% endif %}

            </div>
        </div>
    </nav>

     {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    <p>{{ message }}</p>
                </div>
    {% endfor %}

    {% block content %}
    {% endblock %}
</div>
 <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

templates/books/author-detail.html
{% extends 'base.html' %}
{% block title %} Author Detail{% endblock %}
{% block content %}
    <h3>Author Detail Page</h3>
    <div class="row mt-5">
        <div class="col-3">
            <img src="{{ author.avatar.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-6">
            <h5>{{ author.first_name }}  {{ author.last_name }}</h5>
{#            <span>Published: {{ book.published }}</span> <br>#}
{#            <span>Genres:#}
{#                {% for genr in author.genre.all %}#}
{#                    <a href="" class="fw-light">{{ genr.name }}</a>#}
{#                {% endfor %}#}
{##}
{#            </span>#}
            <p>WEB: {{ author.website }}</p>
            <p>birthdate: {{ author.birthdate }}</p>

            <p>{{ author.about }}</p>
        
        </div>
    <hr>
    </div>
        <div class="row">
        <h3>Books</h3>
        <div class="col-9">
            {% for book in author.books.all %}
    <div class="row mt-5">
        <div class="col-3">
            <img src="{{ book.cover.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-6">
            <h5>{{ book.title }}</h5>
            <span class="my-2">Authors:
                {% for author in book.authors.all %}
                    <a href="{% url 'books:author-detail' author.pk %}" class="fw-bold">
                    {{ author.first_name }} {{ author.last_name }}
                    </a>
                {% endfor %}
            </span><br>
            <span>Published: {{ book.published }}</span> <br>
            <span>Genres:
                {% for genr in book.genre.all %}
                    <a href="" class="fw-light">{{ genr.name }}</a>
                {% endfor %}

            </span>

            <p>{{ book.description }}</p>
            <p>ISBN: {{ book.isbn }}</p>
            <p>Page: {{ book.page }}</p>
        </div>
            {% endfor %}

        </div>


    </div>

{% endblock %}

templates/books/book-detail.html
{% extends 'base.html' %}
{% block title %} Book Detail{% endblock %}
{% block content %}
    <h3>Book Detail Page</h3>
    <div class="row mt-5">
        <div class="col-3">
            <img src="{{ book.cover.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-6">
            <h5>{{ book.title }}</h5>
            <span class="my-2">Authors:
                {% for author in book.authors.all %}
                    <a href="{% url 'books:author-detail' author.pk %}" class="fw-bold">
                    {{ author.first_name }} {{ author.last_name }}
                    </a>
                {% endfor %}
            </span><br>
            <span>Published: {{ book.published }}</span> <br>
            <span>Genres:
                {% for genr in book.genre.all %}
                    <a href="{% url 'books:genre-detail' genr.pk %}" class="fw-light">{{ genr.name }}</a>
                {% endfor %}

            </span>

            <p>{{ book.description }}</p>
            <p>ISBN: {{ book.isbn }}</p>
            <p>Page: {{ book.page }}</p>
        </div>


    </div>
    <hr>
    <div class="row">
        <h3>Reviews</h3>
        <div class="col-9">
            {% for review in book.reviews.all %}
                <div class="card my-2">
                    <div class="card-header">
                        {{ review.user.username }} rated {{ review.rating }}
{#                        {% for n in range(5) %}#}
{#                            <span class="review-star {% if n <= review.rating %}review-star-active{% endif %}">★</span>#}
{#                        {% endfor %}#}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">       {{ review.user.username }}</h5>
                        <p class="card-text">{{ review.body }}</p>
                        <a href="#" class="btn btn-light">Like 👍</a> <span class="fw-lighter">{{ review.like_count }} likes </span>
                    </div>
                </div>
            {% endfor %}

        </div>


    </div>


{% endblock %}

templates/books/book-list.html
{% extends "base.html" %}
{% load static %}
{% block title %} Books {% endblock %}
{% block content %}
    <div class="py-4">
        <h3>Books</h3>
    </div>
    {% for book in books %}
        <div class="row mb-3">
            <div class="col-2">
                <img src="{{ book.cover.url }}" alt="No Pic" class="img-fluid">
            </div>
            <div class="col-6">
                <a href="{% url 'books:book-detail' book.slug %}"> {{ book.title }}</a>
                <p>{{ book.description }}</p>
            </div>
        </div>
    {% empty %}
        <h3>No Books</h3>
    {% endfor %}

{% endblock %}

templates/books/genre-detail.html
{% extends 'base.html' %}
{% block title %} Genre Detail{% endblock %}
{% block content %}
    <h3>{{ genre.name }} Detail Page</h3>
    <div class="row mt-5">
        <div class="col-6">
            <h5>{{ genre.name }} </h5>
            <hr>
    </div>
        <div class="row">
        <h3>Books</h3>
        <div class="col-9">
            {% for book in genre.books.all %}
    <div class="row mt-5">
        <div class="col-3">
            <img src="{{ book.cover.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-6">
            <h5>{{ book.title }}</h5>
            <span class="my-2">Authors:
                {% for author in book.authors.all %}
                    <a href="{% url 'books:author-detail' author.pk %}" class="fw-bold">
                    {{ author.first_name }} {{ author.last_name }}
                    </a>
                {% endfor %}
            </span><br>
            <span>Published: {{ book.published }}</span> <br>
            <span>Genres:
                {% for genr in book.genre.all %}
                    <a href="" class="fw-light">{{ genr.name }}</a>
                {% endfor %}

            </span>

            <p>{{ book.description }}</p>
            <p>ISBN: {{ book.isbn }}</p>
            <p>Page: {{ book.page }}</p>
        </div>
            {% endfor %}

        </div>


    </div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}

        <h3>Home Page</h3>
        
{% endblock %}

templates/user/Login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h3>Login page</h3>
    <form method="post">
    <div class="row">
       <div class="col-5">
           {% csrf_token %}
           {{ form|crispy }}
           <button class="btn btn-primary">Login</button>
       </div>

    </div>
    </form>

{% endblock %}

templates/user/Logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div>
    <form style="text-align: center" method="post">
        {% csrf_token %}
        Are You Sure Log out <br>
        <a>
            <button type="submit">Yes</button>
        </a>
    </form>
        <a href="{% url 'home' %}">
            <button> No</button>
        </a>
    </div>
{% endblock %}

templates/user/Profile.html
{% extends 'base.html' %}
{% block title %} Profile Page{% endblock %}
{% block content %}
    <h3>Profile Page</h3>
    <div class="row mt-5">
        <div class="col-3">
            <img src="{{ User.avatar.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-6">
            <h5>{{ user.username }}</h5>
            <span class="my-2">Books:
                {% for book in user.books.all %}
                    <a href="" class="fw-bold">
                    {{ book.title }}
                    </a>
                {% endfor %}
            </span><br>
{#            <span>Published: {{ book.published }}</span> <br>#}
{#            <span>Genres:#}
{#                {% for genr in book.genre.all %}#}
{#                    <a href="" class="fw-light">{{ genr.name }}</a>#}
{#                {% endfor %}#}
{##}
{#            </span>#}
{##}
{#            <p>{{ book.description }}</p>#}
{#            <p>ISBN: {{ book.isbn }}</p>#}
{#            <p>Page: {{ book.page }}</p>#}
        </div>


    </div>
    <hr>
    <div class="row">
        <h3>Reviews</h3>
        <div class="col-9">
            {% for review in user.reviews.all %}
                <div class="card my-2">
                    <div class="card-header">
                        {{ review.user.username }} rated {{ review.rating }}
{#                        {% for n in range(5) %}#}
{#                            <span class="review-star {% if n <= review.rating %}review-star-active{% endif %}">★</span>#}
{#                        {% endfor %}#}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">       {{ review.user.username }}</h5>
                        <p class="card-text">{{ review.body }}</p>
                        <a href="#" class="btn btn-light">Like 👍</a> <span class="fw-lighter">{{ review.like_count }} likes </span>
                    </div>
                </div>
            {% endfor %}

        </div>


    </div>


{% endblock %}

templates/user/Register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h3>Register page</h3>
    <form method="post">
    <div class="row">
       <div class="col-5">
           {% csrf_token %}
           {{ form|crispy }}
           <button class="btn btn-primary">Register</button>
       </div>

    </div>
    </form>

{% endblock %}